// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3vjl8TR_SWHT4hkLBpd_4ZiYW9TnQEo',
    appId: '1:390345581324:web:32e26a4fee1c78b5201f29',
    messagingSenderId: '390345581324',
    projectId: 'startups-hub',
    authDomain: 'startups-hub.firebaseapp.com',
    storageBucket: 'startups-hub.appspot.com',
    measurementId: 'G-SPEWNFC2WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVwDvCEyIsWtZO0FlKW8vOSiDaryY4EY',
    appId: '1:390345581324:android:b0adf7f106f5b1a0201f29',
    messagingSenderId: '390345581324',
    projectId: 'startups-hub',
    storageBucket: 'startups-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoCPYUbhLejKP1wSKSV875oa7SO6i1XFY',
    appId: '1:390345581324:ios:ea2ee3c1f018015b201f29',
    messagingSenderId: '390345581324',
    projectId: 'startups-hub',
    storageBucket: 'startups-hub.appspot.com',
    iosClientId: '390345581324-4m96j8tsboa6t8bckraid8t0pt06a1fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoCPYUbhLejKP1wSKSV875oa7SO6i1XFY',
    appId: '1:390345581324:ios:aca4f92d61c7787c201f29',
    messagingSenderId: '390345581324',
    projectId: 'startups-hub',
    storageBucket: 'startups-hub.appspot.com',
    iosClientId: '390345581324-hv1470orif0p41kmbt87f6dnoj03fvs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupshub.RunnerTests',
  );
}
